# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2feb5207bca6db05fd9e79516dea2b9dbaa8a82e3964668ced77b76d229551d08809ac5ae3ba83175c52e8c637b601bd0d59c7d43bf41328310c294d8eab8cb2

test:
  secret_key_base: b8ea5d24a04c5f5c8ff154dd7c836f531818485d759fd579c1bad8855a47df4ee210efa8316120bc5a822f2622caf684b7935e26d51ff8ec64ba9d9ac7185ca7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
